name: build images

on:
  push:
    branches: main

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    strategy:
      matrix:
        combo:
          - 'php7.2-node10'
          - 'php7.2-node12'
          - 'php7.2-node14'
          - 'php7.2-node18'
          - 'php7.3-node10'
          - 'php7.3-node12'
          - 'php7.3-node14'
          - 'php7.3-node18'
          - 'php7.4-node10'
          - 'php7.4-node14'
          - 'php7.4-node16'
          - 'php7.4-node18'
          - 'php8.0-node10'
          - 'php8.0-node14'
          - 'php8.0-node16'
          - 'php8.0-node18'
          - 'php8.1-node14'
          - 'php8.1-node16'
          - 'php8.1-node18'
          - 'php8.1-node20'
          - 'php8.2-node14'
          - 'php8.2-node16'
          - 'php8.2-node18'
          - 'php8.2-node20'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Pull, build and push
        uses: docker/build-push-action@v4
        with:
          context: "./${{ matrix.combo }}"
          pull: true
          push: true
          platforms: linux/amd64
          tags: garfieldius/typo3-ci:${{ matrix.combo }}
